export { type Article, ArticleType, ArticleBlockType } from './model/types/article'
export type { ArticleDetailsSchema } from './model/types/articleDetailsSchema'
export { ArticleDetails } from './ui/ArticleDetails/ArticleDetails'
export { articleDetailsReducer } from './model/slice/articleDetailsSlice'
export { getArticleDetailsData } from './model/selectors/getArticleDetails'
