export enum ValidateProfileErrors {
  SERVER_ERROR = 'SERVER_ERROR',
  NO_PROFILE_DATA = 'NO_PROFILE_DATA',
  INCORRECT_USER_DATA = 'INCORRECT_USER_DATA',
  INCORRECT_USER_AGE = 'INCORRECT_USER_AGE',
  INCORRECT_USER_COUNTRY = 'INCORRECT_USER_COUNTRY',
}
